docs/docs/getting_started/cli.md
According to the README importing from postgres seems to be supported now.
=> Importing from a database seems to be supported

docs/blog/2021-03-09-postgres-data-gen.md
- update json examples to use correspondg fake-rs names
- increase phone varchar size as fake-rs unexpectedly exceeds it
- correct PG example password
=> docs: update pg blog to work correctly

examples/bank/bank_db/users.json
https://github.com/getsynth/synth/issues/38
I don't know how to handle `sha256` generator issue. So, I ended up using the `bs_adj` generator for password_hash
=> Fixed the bank_db example #38

README.md, synth/benches/bench.rs, synth/src/cli/mod.rs
Hi, opening a PR for: https://github.com/getsynth/synth/issues/46.
I wasn't very familiar with this package or some of the crates used, so let me know if you have any feedback... thank you!
=> Feature: synth init <directory-name>

.github/workflows/synth-mysql.yml, synth/src/cli/export.rs, synth/src/cli/import.rs, synth/src/datasource/mysql_datasource.rs, synth/testing_harness/mysql/README.md, synth/testing_harness/mysql/e2e.sh
Added support for MariaDB and added related tests
=> feat: added support for MariaDB

synth/src/datasource/postgres_datasource.rs
=> Fix typo timestamptz

.github/workflows/scripts/test_examples.sh, .github/workflows/synth-test-examples.yml
=> ci: Test examples in CI pipeline

.github/workflows/synth-test.yml
Fixes a typo in the clippy workflow.
=> fix(ci): fix clippy workflow

docs/blog/2021-08-04-test-data.md
Thanks to @NodarD for our next blog post. Let's have a final read before pushing it out tomorrow!
=> add blog post by Nodar

docs/blog/2021-08-04-test-data.md
This is now a public domain "test screen" which seems much more apropos.
=> docs: update image on recent blog post

core/src/compile/utils.rs
Addresses an issue where a panic occurs when an error happens in a field targeted by a reference.
=> fix: handle errors through references instead of panicking

core/src/schema/namespace.rs, synth/src/cli/export.rs
=> fix: error out on unknown reference at toposort stage

docs/docs/other/telemetry.md, synth/src/cli/telemetry.rs, tools/install.sh
=> chore: installer enables telemetry

synth/src/datasource/postgres_datasource.rs
This avoids SQL injections in the retrieval of the primary keys for the PostgreSQL data source.
Closes #30
=> fix: avoid SQL injections in PostgreSQL query

docs/docusaurus.config.js
Preview: https://synth-docs-christoshadjiaslanis-getsynth.vercel.app
=> docs: docs logo now takes you to website

README.md, docs/blog/2021-03-08-mern.md, docs/blog/2021-09-07-mocking-a-production-api.md, docs/docs/integrations/postgres.md
=> docs: fix GitHub format

docs/blog/2021-09-27-crash.md
"I give up. I've found 1 way to crash our product with an unintended error, reproduced some known limitations and outlined a number of error messages we can improve on. I fell far short of my original goal, which either means I'm really bad at finding errors, or our code is incredibly reliable. Given the track record of software written in Rust, I'd like to think it's the latter, but I'll leave judgement to you."
=> add blog post: 50 ways to crash our product

.github/workflows/release.yml
Fixes artifact upload broken in #243
=> ci: fix macos artifact upload

core/src/graph/iter.rs, core/src/graph/mod.rs
This node will later be used to generate values from other datasources.
=> feat: IterNode stage 1

shell.nix
Just some tools to needed when developing in a Nix environment :smile:
=> feat: add some missing tools to the dev environment

.github/workflows/synth-errors.yml, Cargo.lock, core/Cargo.toml, core/src/schema/content/array.rs, core/src/schema/content/mod.rs, core/src/schema/content/string.rs, synth/Cargo.toml, synth/testing_harness/errors/README.md, synth/testing_harness/errors/e2e.sh, synth/testing_harness/errors/generate/186-negative-array/errors.txt, synth/testing_harness/errors/generate/186-negative-array/schema.json, synth/testing_harness/errors/generate/190-faker-mistyped/errors.txt, synth/testing_harness/errors/generate/190-faker-mistyped/schema.json, synth/testing_harness/errors/generate/191-format-structure-wrong/errors.txt, synth/testing_harness/errors/generate/191-format-structure-wrong/schema.json, synth/testing_harness/errors/generate/192-string-missing-subtype/errors.txt, synth/testing_harness/errors/generate/192-string-missing-subtype/schema.json, synth/testing_harness/errors/generate/193-array-length-missing-high/errors.txt, synth/testing_harness/errors/generate/193-array-length-missing-high/schema.json, synth/testing_harness/errors/generate/195-empty-array-length/errors.txt, synth/testing_harness/errors/generate/195-empty-array-length/schema.json, synth/testing_harness/errors/generate/array-empty-content/errors.txt, synth/testing_harness/errors/generate/array-empty-content/schema.json, synth/testing_harness/errors/generate/missing-type/errors.txt, synth/testing_harness/errors/generate/missing-type/schema.json
Make error messages more contextual
Closes #186
Closes #192
Closes #195
Closes #191
Closes #190
Partially addresses #193
=> bug: better errors

.github/workflows/release.yml, synth/.cargo/config.toml, tools/install.sh
=> ci: added arm to release builds

.github/workflows/synth-master.yml
=> ci: fixed playground deployment

.github/workflows/release.yml, .github/workflows/synth-bench.yml, .github/workflows/synth-errors.yml, .github/workflows/synth-mongo.yml, .github/workflows/synth-mysql.yml, .github/workflows/synth-postgres.yml, .github/workflows/synth-test.yml, .github/workflows/synth.yml, docs/docs/getting_started/installation.md, rust-toolchain, tools/vagrant/linux/ubuntu/Vagrantfile
build for arm fix introduced bug - missing space in YAML config.
=> trying to fix CI release

dist/playground/Dockerfile
The Playground for Synth was failing CI.
=> Fix: Synth Playground Docker Image

core/src/graph/mod.rs, core/src/graph/number.rs, core/src/lib.rs, core/src/schema/content/categorical.rs, core/src/schema/content/datasource.rs, core/src/schema/content/date_time.rs, core/src/schema/content/mod.rs, core/src/schema/content/number.rs, core/src/schema/content/series.rs, core/src/schema/content/string.rs, core/src/schema/content/unique.rs, core/src/schema/inference/mod.rs, core/src/schema/mod.rs, core/src/schema/namespace.rs, core/src/schema/optionalise.rs, synth/src/cli/csv/headers.rs, synth/src/cli/csv/mod.rs, synth/src/cli/mod.rs
=> Fix: Clippy Complaints

core/Cargo.toml, gen/Cargo.toml
Playground was having more problems, so this will hopefully fix it.
=> fix: Playground

synth/Cargo.toml, synth/src/cli/telemetry.rs
This should fix all of the OpenSSL problems with telemetry.
=> fix: Change posthog-rs to posthog-unofficial

Cargo.lock
This will fix the broken nix compilation.
=> fix: lockfile updated

.github/workflows/release.yml
=> Fix: Typos in Workflows

docs/docs/integrations/index.md, docs/sidebars.js
=> feat: document _type workaround

default.nix, nix/docker.nix, nix/sources.json, nix/sources.nix, nix/toolchain.nix
I noticed the nix package in the Synth repository is out of date compared to the rest of the project.
=> chore: Nix update

core/src/compile/address.rs, core/src/error.rs, core/src/graph/json.rs, core/src/graph/mod.rs, core/src/graph/number.rs, core/src/graph/string/faker.rs, core/src/lib.rs, core/src/schema/content/array.rs, core/src/schema/content/categorical.rs, core/src/schema/content/date_time.rs, core/src/schema/content/hidden.rs, core/src/schema/content/object.rs, core/src/schema/content/string.rs, core/src/schema/content/unique.rs, core/src/schema/mod.rs, core/src/schema/namespace.rs, core/src/schema/scenario.rs, dist/playground/src/app.rs, synth/src/cli/csv/headers.rs, synth/src/cli/csv/mod.rs, synth/src/cli/export.rs, synth/src/cli/jsonl.rs, synth/src/cli/store.rs, synth/src/datasource/mysql_datasource.rs, synth/src/datasource/postgres_datasource.rs, synth/src/datasource/relational_datasource.rs, synth/src/lib.rs, synth/src/main.rs, synth/src/version.rs, synth/tests/docs.rs
Clippy complains about a lot in Synth, and a lot of Clippy complaints are suppressed.
=> chore: address clippy complaints

core/src/graph/number.rs, core/src/schema/content/array.rs, core/src/schema/content/number.rs, core/src/schema/inference/mod.rs, synth/src/datasource/postgres_datasource.rs, synth/testing_harness/postgres/0_complete_schema.sql, synth/testing_harness/postgres/arrays_master/arrays.json, synth/testing_harness/postgres/arrays_master/unofficial_arrays.json, synth/testing_harness/postgres/complete_import_master/types.json, synth/testing_harness/postgres/complete_import_master/unofficial_types.json, synth/testing_harness/postgres/complete_master/types.json
=> feat: i16 support

www/components/Hero.tsx
This should also re-deploy the website, hopefully fixing issues.
=> feat: remove "backed by ycombinator"

docs/docs/integrations/mysql.md
Even though it does not matter as far as port number is concerned, but I loaded 220M records in postgres using Synth so as a token of thanks sending pull request
=> mysql default port is 3306

.github/workflows/synth.yml, Cargo.lock, core/src/error.rs, core/src/graph/iter.rs, core/src/graph/series.rs, docs/blog/2021-08-31-seeding-databases-tutorial.md, synth/src/cli/csv/headers.rs, synth/src/cli/import_utils.rs, synth/src/datasource/mod.rs, synth/src/error.rs
This is the fix for the warnings that I mentioned in some other comments
=> chore: update dependencies and fix associated warnings
