shuttle-hq/synth

Cargo.lock
core/Cargo.toml
core/src/graph/mod.rs
core/src/graph/string/faker.rs
core/src/graph/unique.rs
core/src/schema/content/mod.rs
core/src/schema/content/string.rs
core/src/schema/content/unique.rs
gen/Cargo.toml
gen/src/de.rs
gen/src/error.rs
gen/src/generator/try.rs
gen/src/value.rs

This adds a naive `UniqueNode` type to the generator graph that removes duplicates from values generated by an inner node. This allows to, for example, generate only distinct instances of usernames, addresses, and even works for compound structures like arrays or objects.
This also adds a `UniqueContent` node to the schema in order to make the feature accessible from the JSON schema. An example usage is:
```json
{
"type": "unique",
"content": {
"type": "string",
"date_time": {
"format": "%Y-%m-%dT%H:%M:%S%z",
"begin": "2000-01-01T00:00:00+0000",
"end": "2020-01-01T00:00:00+0000"
}
}
}
```
Closes #10.

feat: Add a Unique node type to remove duplicate values

---

Cargo.lock
core/Cargo.toml
core/src/graph/mod.rs
core/src/graph/string/format.rs
core/src/graph/string/mod.rs
core/src/lib.rs
core/src/schema/content/prelude.rs
core/src/schema/content/string.rs
core/src/schema/inference/mod.rs
docs/docs/content/string.md
gen/src/generator/try.rs

This adds a `RandomString::Format` variant to the generator graph that wraps around [`dynfmt::SimpleCurlyFormat`](https://docs.rs/dynfmt/0.1.5/dynfmt/curly/struct.SimpleCurlyFormat.html). This provides a simplified version of the Rust-style [`format!`](https://doc.rust-lang.org/std/macro.format.html) macro features from within Synth.
Also includes:
* A couple code formatting tweaks
* The addition of a `FormatContent` to the schema, for the feature to be accessible from the JSON schema
* Documentation for the `format` string variant in the JSON schema
* Elementary smoke tests that check the generator works in simple cases
```json
{
"type": "string",
"format": {
"format": "my name is {name} and my email is {email}",
"arguments": {
"name": {
"type": "string",
"faker": {
"generator": …
```

feat: Add a formatter generator

---

.github/workflows/scripts/validate_mysql_gen_count.sh
.github/workflows/synth-mysql.yml
Cargo.lock
synth/Cargo.toml
synth/src/cli/export.rs
synth/src/cli/import.rs
synth/src/cli/import_utils.rs
synth/src/cli/mod.rs
synth/src/cli/mysql.rs
synth/src/cli/postgres.rs
synth/src/datasource/mod.rs
synth/src/datasource/mysql_datasource.rs
synth/src/datasource/postgres_datasource.rs
synth/src/datasource/relational_datasource.rs
synth/src/lib.rs
synth/testing_harness/mysql/0_hospital_schema.sql
synth/testing_harness/mysql/1_hospital_data.sql
synth/testing_harness/mysql/README.md
synth/testing_harness/mysql/e2e.sh
synth/testing_harness/mysql/hospital_master/doctors.json
synth/testing_harness/mysql/hospital_master/hospitals.json
synth/testing_harness/mysql/hospital_master/patients.json
synth/testing_harness/postgres/e2e.sh
tools/vagrant/README.md
tools/vagrant/linux/ubuntu/Vagrantfile

feat: added support for MySql
- Added MySql generate and import support. Included relevant integration tests
- Refactored data base types into modular data sources, increasing shared code among data sources
- Changed SQL client to use sqlx to reduce dependencies increase with additional databases; sqlx also gives us async capability
- Parallelized relational database inserts
- Added vagrant sandbox environment for test and dev
partially resolves #8

Added support for MySql

---

docs/docs/content/string.md

Hi,
I was going through the docs and found a small typo in the [string generator page](https://getsynth.github.io/synth/content/string#faker). This PR simply fixes the typo and improves the related sentence (as well as a missing newline character in the last line 😅).

docs: fix typo in string.md

---

core/src/compile/mod.rs
core/src/schema/augmentation.rs
core/src/schema/content/object.rs
core/src/schema/inference/value.rs
core/src/schema/namespace.rs
synth/src/cli/export.rs
synth/src/cli/import.rs
synth/src/cli/import_utils.rs
synth/src/cli/mod.rs
synth/src/cli/store.rs
synth/src/daemon.rs
synth/src/index.rs

Replace most of anyhow's Context::context by Context::with_context in order to only allocate heap memory when necessary.

perf: optimize anyhow usage to lazily allocate heap memory

---

.github/workflows/synth-bench.yml

Apparently the comment action did not work as expected, so let's try a github script instead.
I also made the workflow to run if itself was updated. Perhaps that's a good idea for all workflows. Will do so in a followup.

another attempt to fix the benchmark workflow

---

.github/workflows/synth-bench.yml

This should sidestep the problem of 403 errors on comment right now while
we figure out a suitable workaround.

bench only on push

---

docs/blog/2021-03-09-postgres-data-gen.md
docs/docs/content/array.md
docs/docs/content/object.md
docs/docs/content/one-of.md
docs/docs/content/same-as.md
docs/docs/examples/bank.md
docs/docs/getting_started/cli.md
docs/docs/getting_started/core-concepts.md
docs/docs/getting_started/hello-world.md
docs/docs/getting_started/installation.md
docs/docs/getting_started/synth.md
docs/docusaurus.config.js
docs/src/pages/index.tsx

- Fixes typos
- Better explanations for `field reference` and other related items
- Also makes paths relative so docs won't break when we change `baseUrl`

docs: Typos, housekeep

---

.github/workflows/synth-test.yml
synth/src/sampler.rs

I believe this should fix the windows test and clippy workflows. There's no need to set "-D warnings" env when testing, as it is already applied when running cargo build. The clippy workflow should now select the nightly binary by default and no longer complain.

Fix clippy and windows test workflows

---

core/src/graph/mod.rs
core/src/schema/content/mod.rs
core/src/schema/content/number.rs
core/src/schema/content/object.rs
core/src/schema/content/one_of.rs
core/src/schema/content/string.rs
core/src/schema/inference/mod.rs
core/src/schema/inference/value.rs
core/src/schema/optionalise.rs
core/src/schema/s_override.rs
docs/docs/content/number.md
docs/docs/content/object.md
docs/docs/content/same-as.md
docs/docs/modifiers.md
docs/sidebars.js
synth/src/cli/import_utils.rs
synth/src/cli/mongo.rs

This
* Re-defines the deserialization of `Content` to support deserializing from literals in the following instances:
* String literals are interpreted as `Content::SameAs` (i.e. references)
* Number literals are interpreted as `Constant` `Content::Number` variants
* Removes `FieldContent`
* The only purpose of `FieldContent` was to allow for the field `optional: bool` to be available in `Content::Object`'s fields. This is now taken care of by `schema::content::ContentLabels`. The change was required because deserialization of `FieldContent` was incompatible with the specification of references as string literals.
* In order to preserve backward compat, the new deserialize impl also allows for the specification of the `optional: bool` and `unique: bool` fields on any Content node.
* It …

feat: Allow the use of some literals wherever Content is accepted

---

gen/src/ser.rs

Fixes an issue arising when, at generation time, a generated value is of an incorrect type to be used as an argument to `format` and a an explicit panic occurs as a result of left-over `todo!`'s.

fix: Error out of malformed streams instead of panicking

---

.github/workflows/release.yml
.github/workflows/synth-bench.yml
.github/workflows/synth-mongo.yml
.github/workflows/synth-mysql.yml
.github/workflows/synth-postgres.yml
.github/workflows/synth-test-examples.yml
.github/workflows/synth.yml

This moves the `RUSTFLAGS` out of the command line into the `env` section of the workflow.

Fix workflows RUSTFLAGS env

---

synth/src/datasource/mysql_datasource.rs
synth/src/datasource/postgres_datasource.rs
synth/src/datasource/relational_datasource.rs

This PR removes the custom parsing of the catalog name for relational databases which used naive string manipulation.
We now instead use built-in database functions like `current_catalog` and `DATABASE()` for PostgreSQL and MySQL respectively.
I've left the fix for MongoDB out of it, as the [official](https://docs.mongodb.com/manual/reference/connection-string/) mongodb connection string does not support specifying the database in the URI. This is going to require the addition of a `--db` flag which is only relevant for the mongodb case:
```
synth import --from mobgodb://localhost:27107 --db my_database my_namespace && synth generate --to mongodb://localhost:27017 --db my_database my_namespace
```
However the current architecture which parses URI strings to build the …

fix: catalog is now inferred automatically for relational databases.

---

.github/workflows/scripts/test_examples.sh
.github/workflows/synth-mongo.yml
.github/workflows/synth-mysql.yml
.github/workflows/synth-postgres.yml
README.md
docs/docs/getting_started/cli.md
docs/docs/getting_started/core-concepts.md
docs/docs/getting_started/hello-world.md
synth/benches/bench.rs
synth/src/cli/mod.rs

This removes `synth init` and references to it in documentation, in CI and README.
Closes #83.

feat: remove synth init

---

.github/workflows/release.yml
synth/Cargo.toml
synth/benches/bench.rs
synth/src/cli/mod.rs
synth/src/cli/telemetry.rs
synth/src/main.rs

This
- refactors the telemetry entrypoint to be more general
- puts the posthog telemetry code under the feature gate `telemetry`, which is disabled by default.
- add the `telemetry` feature flag to GH CI/CD release builds
In particular, users and contributors building from source on `master` will not unnecessarily spam the posthog event stream with WIP issues (i.e. `cargo run`).

feat: feature-gate telemetry

---

synth/src/datasource/postgres_datasource.rs

This is originally from #71, which was by @groogiam. I could not re-open the PR as the original branch was deleted, so I am opening a new PR.
This adds support for `citext` import and export, being treated just like any other string field.
This closes #70, insofar as it adds support for `citext`.

feat: add 'citext' import into string default

---

.github/workflows/docs.yml

I believe the vercel action has two issues:
- It cannot fetch the deployment (even though it actually goes through), which could be permission related
- The deployment is incorrect because the working-directory was not set to ./docs
This fixes the latter. We'll see about the former.

fix: vercel action uses workdir

---

.github/workflows/docs.yml

As mentioned in #138, action does not find deployment on `inspect`.
Looking at the [source](https://github.com/amondnet/vercel-action/blob/58bc126a0052bb8387f8e0b3d72e77562ac7a72f/index.js#L161), it seems like it needs the explicit run variable `scope` to find the deployment for a team target.

fix: vercel action uses scope

---

core/src/schema/content/mod.rs
core/src/schema/content/string.rs
docs/docs/content/string.md

NB: There is an edge case where this will blow up with a `panic` (if `begin` > `end`) with the error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfRangeError(())', core/src/schema/content/string.rs:276:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is a known issue and should be handled separately as it is a non-trivial change to fix this.
Furthermore, behaviour here will deviate from our `number::range` generator (that is, `high` is exclusive and should be strictly bigger than `low`). However in `date_time` this makes less sense as there are different increments for different formats (i.e. nanosecond, second, year etc.). 
If we are to address this it should happen in another PR.

fix: unspecified begin or end params in the datetime will default to now()

---

core/src/graph/array.rs
core/src/graph/mod.rs
core/src/graph/prelude.rs
core/src/graph/string/truncated.rs
core/src/schema/content/array.rs
core/src/schema/content/string.rs
dist/playground/src/app.rs
docs/docs/content/string.md
gen/src/generator/try.rs

The old `truncate` node was breaking a lot of the internal generators API semantics and as a result was implemented in such a way that we couldn't truncate through a reference nor specify the length of the output dynamically.
This re-implements `truncate` to fix those issues.

fix: rewrite truncate node

---

synth/src/sampler.rs

I found this bug when generating data from an empty namespace. Just went to 100% and hang as `generated < target`.

fix: error when sampling from an empty namespace

---

core/src/graph/mod.rs

Fixes an issue where
```json 
{
"type": "array",
"length": {
"type": "number",
"constant": 5
},
"content": {
"type": "null"
}
}
```
cannot generate because the default for
```json
{
"type": "number",
"constant": 5
}
```
is `subtype: u32` but there is no implicit casting `u32 -> u64`, which what an array length expects.

fix: allow u32 as array sizes

---

Cargo.lock
docs/docs/integrations/postgres.md
synth/benches/bench.rs
synth/src/cli/db_utils.rs
synth/src/cli/export.rs
synth/src/cli/import.rs
synth/src/cli/import_utils.rs
synth/src/cli/mod.rs
synth/src/cli/mongo.rs
synth/src/cli/mysql.rs
synth/src/cli/postgres.rs
synth/src/cli/stdf.rs
synth/src/datasource/mysql_datasource.rs
synth/src/datasource/postgres_datasource.rs
synth/src/datasource/relational_datasource.rs

**Summary of Changes**
This PR introduces the idea of a schema to our Postgres support. Schemas are a logical way that Postgres splits up catalogs (databases basically). 
**Old Behavior**
The default schema is `public` when you connect to a PG database and you couldn't specify a schema to connect to. Furthermore the lack of specifying the schema meant that queries which would get primary keys foreign keys etc wouldn't be targeted at a specific schema so things would break.
**New Behavior**
Optionally the schema is specified at the CLI level for import and generate - if no schema is specified it defaults to `public`. When the connection to the database is established there is an explicit check done to see if the schema exists. If it does not a helpful error message tells you so. This …

feat: postgres specify search path

---

.github/workflows/release.yml

Fixes the macos release build by adding a `sudo /usr/sbin/purge` step. This step does not exist on Linux so a new run was added just for macos. An example of this working can be seen [here](https://github.com/chesedo/synth/runs/4124732473?check_suite_focus=true).
This also adds a small `--bin synth` optimization since the release build does not need the playground binary - reduces the build crates from ~260 to ~240.
Closes #216

ci: MacOs release

---

synth/src/cli/import_utils.rs
synth/src/datasource/mysql_datasource.rs
synth/src/datasource/postgres_datasource.rs
synth/src/datasource/relational_datasource.rs
synth/testing_harness/postgres/.gitignore
synth/testing_harness/postgres/0_hospital_schema.sql
synth/testing_harness/postgres/1_hospital_data.sql
synth/testing_harness/postgres/hospital_data_generated_master.json
synth/testing_harness/postgres/hospital_master/patients.json

Adds support to import postgres enums. Generating to postgres enums from string categoricals is already supported.
Closes #104

feat: postgres import enum

---

core/src/graph/mod.rs
core/src/graph/string/constant.rs
core/src/graph/string/mod.rs
core/src/graph/string/sliced.rs
core/src/lib.rs
core/src/schema/content/mod.rs
core/src/schema/content/string.rs
core/src/schema/inference/mod.rs
docs/docs/content/string.md
synth/src/lib.rs

This is a baby step towards #176 - probably it's better to push this into the formatting library eventually though (along with `truncated` which is just a special-case of slicing)

feat: add basic string slicing via the `sliced` generator

---

synth/.cargo/config.toml
synth/Cargo.toml

At least on Linux, building the project was causing the following
warnings to be issued:
warning: synth/Cargo.toml: unused manifest key: target.i686-pc-windows-msvc.rustflags
warning: synth/Cargo.toml: unused manifest key: target.x86_64-pc-windows-msvc.rustflags
These configuration settings were moved from synth/Cargo.toml to
synth/.cargo/config.toml as recommended in the Cargo book
(https://doc.rust-lang.org/cargo/reference/config.html).
Additionally, the configuration file was renamed to config.toml, which
is also recommended by the aforementioned book.

fix(build): remove the "unused manifest key" warning.

---

.github/workflows/cachix.yml
Cargo.lock
default.nix
nix/overlay.nix
nix/sources.json
synth/Cargo.toml

This
- updates some `nix` dependencies to fix the CI and 
- bumps the `Cargo.toml` and `default.nix` version for `synth` to align with release (thus closes #259).

Fix misc build issues

---

synth/Cargo.toml
synth/src/cli/config.rs
synth/src/version.rs

Implement caching for the GitHub GET requests. I defined the cached field to be valid for seven days. Let me know if it should be valid for longer or shorter periods.

feat: cache GitHub GET requests

---

core/src/compile/address.rs
core/src/schema/content/mod.rs
core/src/schema/content/number.rs
synth/src/cli/export.rs
synth/src/cli/mongo.rs

Fixes some clippy warnings:
* https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use
* https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_to_owned

fix: warnings from new clippy lints (relating to `#[must_use]`)

---

core/src/lib.rs
core/src/schema/content/mod.rs
core/src/schema/inference/mod.rs
core/src/schema/mod.rs
core/src/schema/namespace.rs
synth/src/cli/export.rs
synth/src/cli/import.rs
synth/src/cli/import_utils.rs
synth/src/cli/json.rs
synth/src/cli/jsonl.rs
synth/src/cli/mod.rs
synth/src/cli/mongo.rs
synth/src/cli/store.rs
synth/src/cli/telemetry.rs
synth/src/sampler.rs

Removes the `schema::Name` struct entirely. Use regular `String` instead, with necessary checks in place to prevent invalid names. Also made some minor changes to `Namespace` to make it a little bit nicer to work with.
Minor issue: potentially invalid names could be put into a `Namespace` due to the fact that it implements `FromIterator` - I'm not aware of a fallible version of that trait that could be used instead?

refactor: remove `Name` struct

---

synth/src/cli/mod.rs
synth/src/main.rs

Currently, running synth version causes two GET requests to be
dispatched to GitHub in order to check for new Synth versions, wich can
be verified by running RUST_LOG=debug synth version.
This removes the additional request, and now only the child thread
spawned at the main function will be resposible for checking for
updates.

fix: remove trailing GitHub GET request

---

docs/blog/2021-03-08-mern.md
docs/blog/2021-08-31-seeding-databases-tutorial.md
docs/docs/content/index.md
docs/docs/examples/bank.md
docs/docs/getting_started/hello-world.md
docs/docs/other/telemetry.md
www/components/Examples.tsx

While working on #255 I found some references to the deprecated `init` command which this PR removes.
`date_time` examples are also updated in docs or cautions pills added for blog posts to keep their historical value. This closes #267 but not #257 (which has its own PR - #258).
Trailing forward-slashes are also removed from `generate` namespaces to make them cleaner

docs: init and date_time update

---

Cargo.lock
core/src/schema/content/mod.rs
docs/docs/getting_started/cli.md
synth/Cargo.toml
synth/src/cli/csv/headers.rs
synth/src/cli/csv/mod.rs
synth/src/cli/export.rs
synth/src/cli/import.rs
synth/src/cli/mod.rs

Addresses issue: https://github.com/getsynth/synth/issues/33
This PR implements importing and exporting of CSV data to/from Synth schemas. CSV is a very flexible, loosely-defined format so I've had to make some assumptions about how data is formatted - these are as follows:
* Headers are defined using the following syntax: `(name | "[" number "]" ) ( "." name | "[" number "]" )*`
* `[x]` where `x` is some integer defines an value in an array.
* `a.b` is some member `b` of object `a`.
* `a[x][y]` is an element of a 2D array on object member `a`.
* Headers in import data are not mandatory (add `?header_row=false` to `--from` URI) - when headers are not present, a schema is created that generates a flat object with field names in the format `fieldX` where `X` is incremental.
* All rows have …

feat: implement CSV import/export

---

synth/src/cli/config.rs
synth/src/cli/telemetry.rs
synth/src/version.rs

Removes a bunch of `unwrap()` from `Config::save()` to improve our telemetry logs. The change bubbled up to some functions...

refactor: remove unwrap() from Config::save()

---

synth/testing_harness/mongodb/e2e.sh
synth/testing_harness/mysql/e2e.sh
synth/testing_harness/postgres/e2e.sh

Just some e2e testing tweaks I needed lately:
- Making the shebang environment agnostic (like NixOs does not have `/bin/bash`)
- Removing docker container on down else up will fail with container already exists error

refactor: e2e testing

---

README.md

Addresses https://github.com/getsynth/synth/issues/257
Before:
```bash
➜  synth generate try-synth/ --size 2 | jq
Error: Unable to open the namespace "try-synth/"
Caused by:
0: at file try-synth/users.json
1: Failed to parse collection
2: unknown variant `date_time`, expected one of `pattern`, `faker`, `categorical`, `serialized`, `uuid`, `truncated`, `format` at line 29 column 1
```
After:
```bash
➜  synth generate try-synth/ --size 2 | jq
{
"users": [
{
"email": "margarete@example.org",
"id": 1,
"joined_on": "2016-03-04"
},
{
"email": "brody@example.com",
"id": 2,
"joined_on": "2016-07-08"
}
]
}
```

docs: update example to use `date_time` type instead of `string`

---

.github/workflows/synth-postgres.yml
core/src/graph/mod.rs
synth/src/cli/import_utils.rs
synth/src/datasource/mysql_datasource.rs
synth/src/datasource/postgres_datasource.rs
synth/src/datasource/relational_datasource.rs
synth/testing_harness/postgres/.gitignore
synth/testing_harness/postgres/0_hospital_schema.sql
synth/testing_harness/postgres/1_hospital_data.sql
synth/testing_harness/postgres/arrays/0_arrays.sql
synth/testing_harness/postgres/arrays/arrays.json
synth/testing_harness/postgres/arrays/unofficial_arrays.json
synth/testing_harness/postgres/arrays_master/arrays.json
synth/testing_harness/postgres/arrays_master/unofficial_arrays.json
synth/testing_harness/postgres/complete_import_master/types.json
synth/testing_harness/postgres/complete_import_master/unofficial_types.json
synth/testing_harness/postgres/e2e.sh
synth/testing_harness/postgres/hospital_master/hospitals.json

Allows generating and importing postgres arrays to close #171. Also covers array of json generation and json importing to close #67.
- Generating array of Uuids: uuids end up as `Value::String` which cause them to be `text` [here](https://github.com/getsynth/synth/pull/233/files#diff-d9f8a38de3635edbbe1088a44805d801aee9b6c34f91199cc80777016faa1283R282). Adding a `Value::Uuid` type should fix this, I will just need guidance about how please :smile: 
- Generating empty arrays don't work since they cannot be identified [here](https://github.com/getsynth/synth/pull/233/files#diff-d9f8a38de3635edbbe1088a44805d801aee9b6c34f91199cc80777016faa1283R293). But generating an array with min length of 1 as a `one_of` null does work.
- Generating the postgres array of json type (`json[]`) does not work. …

feat: postgres arrays

---

synth/testing_harness/mysql/warnings/i32/i32.json
synth/testing_harness/mysql/warnings/i64/i64.json
synth/testing_harness/mysql/warnings/u32/u32.json
synth/testing_harness/mysql/warnings/u64/u64.json
synth/testing_harness/postgres/arrays/arrays.json
synth/testing_harness/postgres/warnings/i32/i32.json
synth/testing_harness/postgres/warnings/i64/i64.json
synth/testing_harness/postgres/warnings/u32/u32.json
synth/testing_harness/postgres/warnings/u64/u64.json

With the new improved errors, these tests are failing since they could just be `length: 1`

test: fix verbose use of array constant length

---

core/src/graph/mod.rs

While working on #282, I found that `sqlx` will eventually drop the `u32` type for postgres in their 1602 PR. This is likely to happen in a future release of `sqlx`, however this PR gets us ready for once it happens.

refactor: postgres u32

---

synth/build.rs
synth/src/cli/import_utils.rs
synth/src/datasource/mysql_datasource.rs
synth/src/datasource/postgres_datasource.rs
synth/src/datasource/relational_datasource.rs

This reworks `RelationalDataSource` to make it easier to implement sqlx datasources in the future with less code duplication. Born from the #187 discussion

refactor: datasource

---

synth/src/datasource/relational_datasource.rs
synth/testing_harness/mysql/warnings/f32/f32.json
synth/testing_harness/mysql/warnings/f32/schema.sql
synth/testing_harness/mysql/warnings/f32/warnings.txt
synth/testing_harness/mysql/warnings/f64/f64.json
synth/testing_harness/mysql/warnings/f64/schema.sql
synth/testing_harness/mysql/warnings/f64/warnings.txt
synth/testing_harness/postgres/warnings/f32/f32.json
synth/testing_harness/postgres/warnings/f32/schema.sql
synth/testing_harness/postgres/warnings/f32/warnings.txt
synth/testing_harness/postgres/warnings/f64/f64.json
synth/testing_harness/postgres/warnings/f64/schema.sql
synth/testing_harness/postgres/warnings/f64/warnings.txt

This is for our internal clickup issue (1e11y2v) to improve the message shown when trying to generate a f32 to a postgres double precision type.

refactor: more descriptive float warnings

---

core/src/lib.rs
synth/src/lib.rs

I didn't see async closures anywhere in the code, so I removed the declaration. Works toward #345.

Refactor: Remove async closure nightly feature

---

Cargo.lock
synth/Cargo.toml
synth/src/cli/telemetry.rs

The telemetry features is untested, so a typo caused an error during the previous release.

fix: telemetry, bump version

---

README.md
docs/docs/getting_started/installation.md
tools/install.sh

On mac `/usr/local/bin` is owned by root an may lead people to sudo or chown. Enable users to specify install path.

Feat: Enable setting the install path

---

www/vercel.json

On #387 it was noticed that the install.sh on the website was not getting updated. This PR makes the website use the github asset.

fix: change the location of install.sh

---

.github/workflows/release.yml
.github/workflows/synth-bench.yml
.github/workflows/synth-errors.yml
.github/workflows/synth-mongo.yml
.github/workflows/synth-mysql.yml
.github/workflows/synth-postgres.yml
.github/workflows/synth-test.yml
.github/workflows/synth.yml
core/src/lib.rs
docs/docs/getting_started/installation.md
rust-toolchain
synth/src/error.rs
synth/src/lib.rs
synth/src/sampler.rs
synth/tests/docs.rs
test_macros/src/lib.rs
tools/vagrant/linux/ubuntu/Vagrantfile

fix: change .chain() to .sources() to use new Rust

---

.github/workflows/release.yml
.github/workflows/synth-bench.yml
.github/workflows/synth-errors.yml
.github/workflows/synth-mongo.yml
.github/workflows/synth-mysql.yml
.github/workflows/synth-postgres.yml
.github/workflows/synth-test.yml
.github/workflows/synth.yml

Addresses #399. There is still one use of actions-rs left, for using cross, but I haven't found any alternative.

chore: remove most uses of actions-rs

---

.github/workflows/release.yml
.github/workflows/synth-errors.yml
.github/workflows/synth-mongo.yml

In #400 changes introduced typos into the github workflows.

fix: fix typos in workflows

---

README.md

The maintainer notice isn't really needed anymore and it clutters the README.

docs: remove maintainer notice

---

Cargo.lock
core/src/graph/iter.rs
core/src/graph/series.rs
core/src/graph/string/format.rs
core/src/schema/content/date_time.rs
core/src/schema/scenario.rs
synth/Cargo.toml
synth/src/cli/mongo.rs
synth/src/utils.rs

cargo-audit says a few of the dependencies have vulnerabilities, so it is a good idea to update them.

chore: update dependency versions

---

Cargo.lock
core/src/graph/number.rs
core/src/schema/content/number.rs
core/src/schema/optionalise.rs
synth/Cargo.toml
synth/src/cli/csv/mod.rs

This fix will address #432, which was caused by an unchecked `unwrap()` after trying to convert a F64 value to a JSON Number. Since JSON Numbers cannot wrap `NaN` or `Inf` values, this would previously fail if encountering a string of the form `"Nan"` or `"Inf"`
Additionally, this change bumps up the version of the `log` dependency in `synth/Cargo.toml` from `0.4.11` to `0.4.18` to fix a compilation issue on recent nightly toolchains (see [this issue in async-std for more info](https://github.com/async-rs/async-std/issues/1058))

fix: Fix panic during CSV import when encountering invalid floats

---

.github/workflows/cachix.yml

Cachix is still failing, this might fix it. #434.

fix: versions for GH actions are behind

---

Cargo.lock
core/src/graph/number.rs
core/src/schema/content/array.rs
core/src/schema/content/number.rs
core/src/schema/inference/mod.rs
synth/src/datasource/mysql_datasource.rs
synth/testing_harness/mysql/0_hospital_schema.sql
synth/testing_harness/mysql/1_hospital_data.sql
synth/testing_harness/mysql/README.md
synth/testing_harness/mysql/e2e.sh
synth/testing_harness/mysql/hospital_master/doctors.json
synth/testing_harness/mysql/hospital_master/hospitals.json
synth/testing_harness/mysql/hospital_master/patients.json
synth/testing_harness/mysql/warnings/f64/warnings.txt

Hi friends!
Came across an issue when trying to `import` from a MySQL source on a schema that made use of `TINYINT` columns, and found a couple of other discrepancies with what I understood to be the type translation as [specified in the docs](https://www.getsynth.com/docs/integrations/mysql).
I am not very experienced in Rust, and I am primarily basing the work here on [prior art](https://github.com/shuttle-hq/synth/pull/405).
We'll probably want the following:
* Extend the test scenarios to the Postgres cases, and/or confirm that these changes don't break some changes somewhere
* Bump a version - I think these might be considered breaking changes somewhat
* Add support for `u8` as well?
* This will also make the testing schema modification I made less nonsensical, I don't know what …

Implement `i8` and detect types correctly in MySQL
